# Generated by Django 3.0.8 on 2020-09-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='downloadlink',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='track',
            name='variantscsv',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
