# Generated by Django 3.1.4 on 2021-06-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_createmawi'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='layout',
            field=models.CharField(default='', max_length=128),
        ),
    ]
