# Generated by Django 3.1.4 on 2021-02-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_auto_20200915_1533'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Track',
        ),
    ]
