# Generated by Django 4.0.6 on 2022-07-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_track_free_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='slug',
            field=models.CharField(default='-', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(default='-', max_length=128, unique=True),
        ),
    ]
