# Generated by Django 3.1.4 on 2021-02-05 11:02

from django.db import migrations, models
import django.db.models.deletion
import races.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('js', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RaceSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(default='no description')),
                ('tgz', models.FileField(blank=True, null=True, upload_to='tgz/')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('car_download_url', models.URLField(blank=True, default='')),
                ('track_download_url', models.URLField(blank=True, default='')),
                ('fixed_cars', models.BooleanField(default=False)),
                ('randomizable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.poll')),
                ('racesetup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.racesetup')),
            ],
        ),
        migrations.CreateModel(
            name='RaceQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.racesetup')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ts', models.DateTimeField(default=races.models.set_start_timestamp)),
                ('stdout', models.TextField(default='')),
                ('stderr', models.TextField(default='')),
                ('end_ts', models.DateTimeField(null=True)),
                ('racesetup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.racesetup')),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='racesetups',
            field=models.ManyToManyField(through='races.Voting', to='races.RaceSetup'),
        ),
    ]
