# Generated by Django 3.0.8 on 2020-07-27 19:17

from django.db import migrations, models
import django.db.models.deletion
import races.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('js', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RaceSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(default='no description')),
                ('tgz', models.FileField(upload_to='')),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.Poll')),
                ('racesetup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.RaceSetup')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ts', models.DateTimeField(default=races.models.set_start_timestamp, unique=True)),
                ('stdout', models.TextField(default='')),
                ('stderr', models.TextField(default='')),
                ('racesetup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='races.RaceSetup')),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='racesetups',
            field=models.ManyToManyField(through='races.Voting', to='races.RaceSetup'),
        ),
    ]
