# Generated by Django 3.0.8 on 2020-07-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='start_ts',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='racesetup',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='racesetup',
            name='tgz',
            field=models.FileField(upload_to='tgz/'),
        ),
    ]
