# Generated by Django 3.1.4 on 2021-02-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesetup',
            name='car_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='racesetup',
            name='track_override',
            field=models.BooleanField(default=False),
        ),
    ]
