# Generated by Django 3.0.8 on 2020-07-30 16:20

from django.db import migrations, models
import races.models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_auto_20200730_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='end_ts',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='start_ts',
            field=models.DateTimeField(default=races.models.set_start_timestamp),
        ),
    ]
