# Generated by Django 3.1.4 on 2021-02-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_auto_20210207_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racesetup',
            name='car_download_url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='racesetup',
            name='track_download_url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
    ]
