# Generated by Django 3.0.8 on 2020-07-30 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0003_auto_20200730_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='racesetup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='races.RaceSetup'),
            preserve_default=False,
        ),
    ]
