# Generated by Django 3.0.8 on 2020-09-15 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_auto_20200915_1533'),
        ('cars', '0001_initial'),
        ('races', '0004_auto_20200730_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesetup',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.Car'),
        ),
        migrations.AddField(
            model_name='racesetup',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracks.Track'),
        ),
        migrations.AlterField(
            model_name='racesetup',
            name='tgz',
            field=models.FileField(blank=True, null=True, upload_to='tgz/'),
        ),
    ]
