# Generated by Django 3.0.8 on 2020-09-15 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('tracks', '0002_auto_20200915_1533'),
        ('races', '0005_auto_20200915_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racesetup',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.Car'),
        ),
        migrations.AlterField(
            model_name='racesetup',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracks.Track'),
        ),
    ]
