# Generated by Django 3.1.4 on 2021-03-04 11:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0005_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesetup',
            name='start_ts',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 11, 24, 11, 5, 25, 827169, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
