# Generated by Django 3.1.4 on 2021-03-04 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0006_racesetup_start_ts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='racesetup',
            old_name='start_ts',
            new_name='created',
        ),
    ]
