# Generated by Django 3.1.4 on 2020-12-27 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0006_auto_20200915_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.racesetup')),
            ],
        ),
    ]
