# Generated by Django 3.1.4 on 2021-03-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0007_auto_20210304_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesetup',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
