# Generated by Django 3.1.4 on 2021-01-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0007_racequeue'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesetup',
            name='car_download_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='racesetup',
            name='track_download_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
