# Generated by Django 3.1.4 on 2021-05-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0008_racesetup_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='racequeue',
            name='options',
            field=models.TextField(default=''),
        ),
    ]
