# Generated by Django 3.1.4 on 2021-01-19 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0008_auto_20210119_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racesetup',
            name='car',
        ),
        migrations.RemoveField(
            model_name='racesetup',
            name='track',
        ),
    ]
