# Generated by Django 3.1.4 on 2021-06-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0009_racequeue_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesetup',
            name='imgurlink',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
    ]
