# Generated by Django 3.1.4 on 2021-01-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0009_auto_20210119_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesetup',
            name='fixed_cars',
            field=models.BooleanField(default=True),
        ),
    ]
