# Generated by Django 3.1.4 on 2021-01-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0010_racesetup_fixed_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesetup',
            name='randomizable',
            field=models.BooleanField(default=True),
        ),
    ]
