# Generated by Django 3.1.14 on 2022-07-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0010_racesetup_imgurlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesetup',
            name='tierdrop',
            field=models.BooleanField(default=False),
        ),
    ]
