# Generated by Django 3.1.4 on 2021-01-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0011_racesetup_randomizable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racesetup',
            name='fixed_cars',
            field=models.BooleanField(default=False),
        ),
    ]
