# Generated by Django 4.1 on 2022-08-24 15:23

from django.db import migrations
# import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0011_racesetup_tierdrop'),
    ]

    operations = [
 #       migrations.AlterField(
 #           model_name='racesetup',
 #           name='image',
 #           field=thumbnails.fields.ImageField(null=True, upload_to='images/'),
 #       ),
    ]
