# Generated by Django 4.1 on 2022-08-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0012_alter_racesetup_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racesetup',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
