# Generated by Django 4.1 on 2022-09-08 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0015_racesetup_date_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='racesetup',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='racesetup',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='racesetup',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.DeleteModel(
            name='Race',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.DeleteModel(
            name='Voting',
        ),
    ]
