# Generated by Django 3.1.14 on 2022-07-09 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('races', '0010_racesetup_imgurlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdhocRace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ts', models.DateTimeField(auto_now_add=True)),
                ('end_ts', models.DateTimeField(default=None, null=True)),
                ('stderr', models.TextField(default='')),
                ('stdout', models.TextField(default='')),
                ('result', models.JSONField(null=True)),
                ('practice_minutes', models.IntegerField(default=0)),
                ('qualifying_minutes', models.IntegerField(default=10)),
                ('race_minutes', models.IntegerField(default=15)),
                ('racesetup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.racesetup')),
            ],
        ),
    ]
