# Generated by Django 4.0.6 on 2022-07-21 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0011_racesetup_tierdrop'),
        ('adhoc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdhocRaceQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('options', models.TextField(default='')),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.racesetup')),
            ],
        ),
    ]
