# Generated by Django 4.1 on 2022-08-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhoc', '0003_adhocrace_admin_password_adhocrace_fixed_setups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhocrace',
            name='end_ts',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='adhocrace',
            name='join_password',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='adhocrace',
            name='result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adhocrace',
            name='stderr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adhocrace',
            name='stdout',
            field=models.TextField(blank=True, default=''),
        ),
    ]
