# Generated by Django 4.1 on 2022-08-26 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adhoc', '0005_alter_adhocrace_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adhocracequeue',
            name='options',
        ),
        migrations.AlterField(
            model_name='adhocracequeue',
            name='setup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adhoc.adhocrace'),
        ),
    ]
