# Generated by Django 4.1 on 2022-08-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhoc', '0007_rename_setup_adhocracequeue_adhocrace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhocrace',
            name='start_ts',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
