# Generated by Django 4.1 on 2022-09-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhoc', '0010_adhocrace_start_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhocrace',
            name='run_forever',
            field=models.BooleanField(default=False),
        ),
    ]
