# Generated by Django 3.0.8 on 2020-09-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
                ('uid', models.CharField(max_length=128, unique=True)),
                ('setup', models.TextField(blank=True, default='')),
                ('skinscsv', models.CharField(blank=True, default='', max_length=512)),
                ('downloadlink', models.URLField(blank=True, default='')),
            ],
        ),
    ]
