# Generated by Django 3.1.4 on 2021-06-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('rsr_id', models.IntegerField(default=0)),
                ('dlc_slug', models.CharField(blank=True, default='', max_length=128)),
                ('download_url', models.URLField(blank=True, default='', max_length=2048)),
            ],
        ),
    ]
