# Generated by Django 3.1.4 on 2021-06-01 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        ('tracks', '0001_initial'),
        ('cars', '0002_laptime'),
    ]

    operations = [
#        migrations.AddField(
#            model_name='laptime',
#            name='driver',
#            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.driver'),
#        ),
#        migrations.AddField(
#            model_name='laptime',
#            name='track',
#            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.track'),
#        ),
    ]
