# Generated by Django 3.1.14 on 2022-07-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20210601_1153'),
    ]

    operations = [
#        migrations.AddField(
#            model_name='laptime',
#            name='best',
#            field=models.FloatField(null=True),
#        ),
#        migrations.AddField(
#            model_name='laptime',
#            name='middle',
#            field=models.FloatField(null=True),
#        ),
#        migrations.AddField(
#            model_name='laptime',
#            name='num_entries',
#            field=models.IntegerField(null=True),
#        ),
#        migrations.AddField(
#            model_name='laptime',
#            name='worst',
#            field=models.FloatField(null=True),
#        ),
    ]
